
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MuskokaCamp
{

using System;
    using System.Collections.Generic;
    
public partial class camperProfile
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public camperProfile()
    {

        this.registrationDates = new HashSet<registrationDate>();

        this.payments = new HashSet<payment>();

    }


    public int camperID { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public string familyName { get; set; }

    public int age { get; set; }

    public string rate { get; set; }

    public string address { get; set; }

    public string contactName { get; set; }

    public string contactRelation { get; set; }

    public string contactNumber { get; set; }

    public string importantNotes { get; set; }

    public byte[] photo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<registrationDate> registrationDates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<payment> payments { get; set; }

}

}
