

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MuskokaCamp
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class muskokaEntities : DbContext
{
    public muskokaEntities()
        : base("name=muskokaEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<camperProfile> camperProfiles { get; set; }

    public virtual DbSet<payment> payments { get; set; }

    public virtual DbSet<registrationDate> registrationDates { get; set; }

}

}

